package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"unicode"
)

const (
	blockShift = 8
	blockSize  = 1 << blockShift
	blockMask  = blockSize - 1
)

func foldRepr(r rune) rune {
	min := r
	for x := unicode.SimpleFold(r); x != r; x = unicode.SimpleFold(x) {
		if x < min {
			min = x
		}
	}
	return min
}

func compact(delta []int32) (index []uint16, values []int32) {
	nBlocks := (len(delta) + blockMask) >> blockShift
	seen := map[string]uint16{}
	for b := 0; b < nBlocks; b++ {
		start := b << blockShift
		blk := make([]int32, blockSize)
		for i := 0; i < blockSize && start+i < len(delta); i++ {
			blk[i] = delta[start+i]
		}
		key := blockKey(blk)
		id, ok := seen[key]
		if !ok {
			id = uint16(len(values) >> blockShift)
			seen[key] = id
			values = append(values, blk...)
		}
		index = append(index, id)
	}
	return index, values
}

func blockKey(blk []int32) string {
	var b bytes.Buffer
	for _, v := range blk {
		b.WriteByte(byte(v))
		b.WriteByte(byte(v >> 8))
		b.WriteByte(byte(v >> 16))
		b.WriteByte(byte(v >> 24))
	}
	return b.String()
}

func main() {
	maxRune := 0
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if unicode.ToLower(r) != r || unicode.ToUpper(r) != r || foldRepr(r) != r {
			if int(r) > maxRune {
				maxRune = int(r)
			}
		}
	}

	n := maxRune + 1
	lowerDelta := make([]int32, n)
	upperDelta := make([]int32, n)
	foldDelta := make([]int32, n)
	for r := 0; r < n; r++ {
		lowerDelta[r] = int32(unicode.ToLower(rune(r)) - rune(r))
		upperDelta[r] = int32(unicode.ToUpper(rune(r)) - rune(r))
		foldDelta[r] = int32(foldRepr(rune(r)) - rune(r))
	}

	li, lv := compact(lowerDelta)
	ui, uv := compact(upperDelta)
	fi, fv := compact(foldDelta)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by internal/gencase, DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package strings2\n\n")
	fmt.Fprintf(&buf, "const caseMaxRune = 0x%x\n", maxRune)
	fmt.Fprintf(&buf, "const caseBlockShift = %d\n", blockShift)
	fmt.Fprintf(&buf, "const caseBlockMask = 0x%x\n\n", blockMask)
	total := len(lv)*4 + len(uv)*4 + len(fv)*4 + (len(li)+len(ui)+len(fi))*2
	fmt.Fprintf(&buf, "// tables cover runes 0..0x%x, approx %d bytes total\n\n", maxRune, total)

	writeU16(&buf, "lowerIndex", li)
	writeI32(&buf, "lowerValues", lv)
	writeU16(&buf, "upperIndex", ui)
	writeI32(&buf, "upperValues", uv)
	writeU16(&buf, "foldIndex", fi)
	writeI32(&buf, "foldValues", fv)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, buf.String())
		panic(err)
	}
	if err := os.WriteFile("casetables.go", src, 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("casetables.go: maxRune=0x%x lower(idx=%d val=%d) upper(idx=%d val=%d) fold(idx=%d val=%d) ~%dKB\n",
		maxRune, len(li), len(lv), len(ui), len(uv), len(fi), len(fv), total/1024)
}

func writeU16(b *bytes.Buffer, name string, v []uint16) {
	fmt.Fprintf(b, "var %s = [...]uint16{", name)
	for i, x := range v {
		if i%16 == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(b, "%d,", x)
	}
	b.WriteString("\n}\n\n")
}

func writeI32(b *bytes.Buffer, name string, v []int32) {
	fmt.Fprintf(b, "var %s = [...]int32{", name)
	for i, x := range v {
		if i%16 == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(b, "%d,", x)
	}
	b.WriteString("\n}\n\n")
}
